YIELD_STRENGTH_FEATURES_GENERAL: list[str] = [
    "Fe",
    "Cr",
    "Ni",
    "Mo",
    "Mn",
    "C",
    "Ti",
    "Si",
    "V",
    "P",
    "S",
    "Cu",
    "W",
    "HT stage 1 temperature",
    "HT stage 1 duration",
    "HT stage 1 cooling",
    "HT stage 2 temperature",
    "HT stage 2 duration",
    "Temperature",
]

LONG_TERM_STRENGTH_FEATURES_GENERAL: list[str] = [
    "Fe",
    "Cr",
    "Ni",
    "Mo",
    "Mn",
    "C",
    "Nb",
    "V",
    "Temperature",
    "HT stage 1 temperature",
    "HT stage 1 duration",
    "HT stage 1 cooling",
    "HT stage 2 temperature",
    "HT stage 2 duration",
    "logt",
]

YIELD_STRENGTH_FEATURES_THERMOCALC: list[str] = [
    "Fe",
    "Cr",
    "Ni",
    "Mo",
    "Mn",
    "C",
    "Si",
    "V",
    "P",
    "S",
    "Cu",
    "HT stage 1 temperature",
    "HT stage 1 duration",
    "HT stage 2 temperature",
    "HT stage 2 duration",
]

TOUGHNESS_FEATURES: list[str] = [
    "Cr",
    "Ni",
    "Mo",
    "Mn",
    "C",
    "Ti",
    "Si",
    "V",
    "P",
    "S",
    "Cu",
    "W",
    "HT stage 1 temperature",
    "HT stage 1 duration",
    "HT stage 1 cooling",
    "HT stage 2 temperature",
    "HT stage 2 duration",
    "Temperature",
]
